#!/usr/bin/env node
/**
 * Interactive .env.local generator (VAPID, dev user, API URL).
 * Run: npm run setup
 */

const fs = require('fs')
const path = require('path')
const readline = require('readline')
const { execSync } = require('child_process')

const ROOT = path.join(__dirname, '..')
const ENV_PATH = path.join(ROOT, '.env.local')

function question(rl, q) {
  return new Promise((resolve) => rl.question(q, resolve))
}

function checkNode() {
  const major = parseInt(process.versions.node.split('.')[0], 10)
  if (major < 18) {
    console.error(
      `[setup] Node 18+ required (found ${process.version}). Please upgrade Node.js.`
    )
    process.exit(1)
  }
  console.log(`[setup] Node ${process.version} — OK`)
}

function checkDocker() {
  try {
    const v = execSync('docker --version', { encoding: 'utf8' }).trim()
    console.log(`[setup] Docker — ${v}`)
  } catch {
    console.warn(
      '[setup] Docker not found (optional for local dev without compose).'
    )
  }
}

async function main() {
  checkNode()
  checkDocker()

  let webpush
  try {
    webpush = require('web-push')
  } catch {
    console.error('[setup] Missing devDependency "web-push". Run: npm install')
    process.exit(1)
  }

  const keys = webpush.generateVAPIDKeys()
  console.log('[setup] Generated a new VAPID key pair.')

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  const apiUrl = (
    await question(rl, 'API base URL (NEXT_PUBLIC_API_URL, e.g. http://localhost:8080): ')
  ).trim()
  const devUserId = (
    await question(
      rl,
      'Dev user id for UI until auth ships (NEXT_PUBLIC_DEV_USER_ID, UUID): '
    )
  ).trim()
  const siteUrl = (
    await question(rl, 'Public site URL (SITE_URL, e.g. http://localhost:3000): ')
  ).trim()

  rl.close()

  if (!apiUrl || !devUserId) {
    console.error('[setup] API URL and dev user id are required.')
    process.exit(1)
  }

  const site = siteUrl || 'http://localhost:3000'

  const lines = [
    '# Generated by scripts/setup.js — do not commit',
    `NEXT_PUBLIC_API_URL=${apiUrl}`,
    `NEXT_PUBLIC_DEV_USER_ID=${devUserId}`,
    `NEXT_PUBLIC_DEV_EMAIL=dev@local.test`,
    `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${keys.publicKey}`,
    `VAPID_PRIVATE_KEY=${keys.privateKey}`,
    `VAPID_SUBJECT=mailto:you@example.com`,
    `SITE_URL=${site}`,
    `WEBHOOK_SECRET=${require('crypto').randomBytes(32).toString('hex')}`,
    '',
  ]

  if (fs.existsSync(ENV_PATH)) {
    const bak = `${ENV_PATH}.bak.${Date.now()}`
    fs.copyFileSync(ENV_PATH, bak)
    console.log(`[setup] Existing .env.local backed up to ${path.basename(bak)}`)
  }

  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf8')
  console.log(`[setup] Wrote ${path.relative(ROOT, ENV_PATH)}`)
  console.log('')
  console.log('Next: start Postgres/MinIO/API via root `docker compose up`, then `npm run dev` in client.')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
