#!/usr/bin/env node
/**
 * Interactive .env.local generator + environment checks (Node, Docker, VAPID via web-push).
 * Run: npm run setup
 */

const fs = require('fs')
const path = require('path')
const readline = require('readline')
const { execSync } = require('child_process')

const ROOT = path.join(__dirname, '..')
const ENV_PATH = path.join(ROOT, '.env.local')

function question(rl, q) {
  return new Promise((resolve) => rl.question(q, resolve))
}

function checkNode() {
  const major = parseInt(process.versions.node.split('.')[0], 10)
  if (major < 18) {
    console.error(
      `[setup] Node 18+ required (found ${process.version}). Please upgrade Node.js.`
    )
    process.exit(1)
  }
  console.log(`[setup] Node ${process.version} — OK`)
}

function checkDocker() {
  try {
    const v = execSync('docker --version', { encoding: 'utf8' }).trim()
    console.log(`[setup] Docker — ${v}`)
  } catch {
    console.warn(
      '[setup] Docker not found (optional for local dev without compose).'
    )
  }
}

async function main() {
  checkNode()
  checkDocker()

  let webpush
  try {
    webpush = require('web-push')
  } catch {
    console.error('[setup] Missing devDependency "web-push". Run: npm install')
    process.exit(1)
  }

  const keys = webpush.generateVAPIDKeys()
  console.log('[setup] Generated a new VAPID key pair (save these in secrets / .env.local).')

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  const supabaseUrl = (await question(rl, 'Supabase URL (NEXT_PUBLIC_SUPABASE_URL): ')).trim()
  const supabaseAnon = (await question(
    rl,
    'Supabase anon key (NEXT_PUBLIC_SUPABASE_ANON_KEY): '
  )).trim()
  const siteUrl = (
    await question(rl, 'Public site URL for push links (SITE_URL, e.g. https://app.example.com): ')
  ).trim()

  rl.close()

  if (!supabaseUrl || !supabaseAnon) {
    console.error('[setup] Supabase URL and anon key are required.')
    process.exit(1)
  }

  const site = siteUrl || 'http://localhost:3000'

  const lines = [
    '# Generated by scripts/setup.js — do not commit',
    `NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnon}`,
    `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${keys.publicKey}`,
    `VAPID_PRIVATE_KEY=${keys.privateKey}`,
    `VAPID_SUBJECT=mailto:you@example.com`,
    `SITE_URL=${site}`,
    `WEBHOOK_SECRET=${require('crypto').randomBytes(32).toString('hex')}`,
    '',
    '# Copy NEXT_PUBLIC_VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT, SITE_URL, WEBHOOK_SECRET',
    '# to Supabase Edge Function secrets for push-notifier.',
    '',
  ]

  if (fs.existsSync(ENV_PATH)) {
    const bak = `${ENV_PATH}.bak.${Date.now()}`
    fs.copyFileSync(ENV_PATH, bak)
    console.log(`[setup] Existing .env.local backed up to ${path.basename(bak)}`)
  }

  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf8')
  console.log(`[setup] Wrote ${path.relative(ROOT, ENV_PATH)}`)
  console.log('')
  console.log('Next:')
  console.log('  1. Apply migrations: supabase db push (or paste SQL from supabase/migrations).')
  console.log('  2. Deploy function: supabase functions deploy push-notifier')
  console.log('  3. Set Edge secrets to match VAPID_*, SITE_URL, WEBHOOK_SECRET, SUPABASE_SERVICE_ROLE_KEY.')
  console.log('  4. Create Database Webhook on public.messages INSERT → function URL; header x-webhook-secret.')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
