listening-port=3478
tcp-listening-port=3478
fingerprint
lt-cred-mech
# USE THE CREDENTIALS FROM .ENV
realm=onetothree.ru
external-ip=5.187.0.150
min-port=49152
max-port=65535
# Ensure it points to the turndb or uses static users from env
no-stdout-log
no-loopback-peers
no-multicast-peers